package app

import (
	"fmt"
	"os"
	"text/tabwriter"
)

// printUsage 顯示所有可用指令的摘要說明。
func (c *cliApp) printUsage() {
	fmt.Println()
	fmt.Println("  XWATCH")
	fmt.Printf("   - version: %s\n", c.version)
	fmt.Println()
	fmt.Println("============================================================")
	fmt.Println("指令列表：")
	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	fmt.Fprintln(w, "  init [help] <subcommand>\t初始化監控設定")
	fmt.Fprintln(w, "  status\t顯示服務狀態、版本與設定摘要")
	fmt.Fprintln(w, "  start\t啟動服務（同步顯示各功能聯動啟動狀態）")
	fmt.Fprintln(w, "  stop\t停止服務（同步顯示各功能聯動停止狀態）")
	fmt.Fprintln(w, "  remove\t停止並移除服務及所有排程")
	fmt.Fprintln(w, "  db [help] <subcommand>\t管理事件資料庫")
	fmt.Fprintln(w, "  export [help] <subcommand>\t匯出監控事件記錄")
	fmt.Fprintln(w, "  mail [help] <subcommand>\t郵件排程管理")
	fmt.Fprintln(w, "  heartbeat [help] <subcommand>\t管理心跳測試")
	fmt.Fprintln(w, "  filecheck [help] <subcommand>\t監控指定目錄內的檔案存在性")
	fmt.Fprintln(w, "  env [help] [set dev|prod]\t切換執行環境")
	fmt.Fprintln(w, "  clear\t清除終端機畫面")
	_ = w.Flush()
	fmt.Println("============================================================")
}

// printInitHelp 顯示 init 指令的詳細說明。
func printInitHelp() {
	fmt.Println()
	fmt.Println("init — 初始化 XWatch 監控設定")
	fmt.Println()
	fmt.Println("用法：")
	fmt.Println("  init [--root PATH] [--install-service]")
	fmt.Println()
	fmt.Println("參數說明：")
	w := tabwriter.NewWriter(os.Stdout, 2, 0, 2, ' ', 0)
	fmt.Fprintln(w, "  --root PATH\t指定監控根目錄（絕對或相對路徑）。")
	fmt.Fprintln(w, "  \t省略時以執行檔所在目錄作為根目錄。")
	fmt.Fprintln(w, "  --install-service\t初始化完成後同時將 XWatch 註冊為 Windows 服務並立即啟動。")
	fmt.Fprintln(w, "  \t若服務已存在則更新設定後重新啟動。")
	_ = w.Flush()
	fmt.Println()
	fmt.Println("執行步驟：")
	fmt.Println("  [1/3] 確認根目錄存在（不存在時詢問是否自動建立）")
	fmt.Println("  [2/3] 將設定寫入 %ProgramData%\\go-xwatch\\config.json")
	fmt.Println("  [3/3] 若加入 --install-service：向 Windows SCM 註冊服務並啟動")
	fmt.Println()
	fmt.Println("範例：")
	fmt.Println("  # 使用執行檔目錄作為根目錄（僅寫入設定，不安裝服務）")
	fmt.Println("  xwatch init")
	fmt.Println()
	fmt.Println("  # 指定目錄並安裝服務（需以系統管理員執行）")
	fmt.Println("  xwatch init --root D:\\data\\watch --install-service")
	fmt.Println()
	fmt.Println("  # 已有服務時重新指定根目錄")
	fmt.Println("  xwatch init --root D:\\new-data --install-service")
	fmt.Println()
	fmt.Println("注意事項：")
	fmt.Println("  - 安裝 Windows 服務需要系統管理員權限")
	fmt.Println("  - 根目錄不存在時程式會詢問是否自動建立")
	fmt.Println("  - 重複執行 init 不會清除已有的事件資料庫")
}

// printDBHelp 顯示 db 指令的詳細說明。
func printDBHelp() {
	fmt.Println()
	fmt.Println("db — 管理 XWatch 事件資料庫")
	fmt.Println()
	fmt.Println("用法：")
	fmt.Println("  db <subcommand>")
	fmt.Println()
	fmt.Println("子指令：")
	w := tabwriter.NewWriter(os.Stdout, 2, 0, 2, ' ', 0)
	fmt.Fprintln(w, "  clear\t清除所有事件記錄（操作不可逆）")
	fmt.Fprintln(w, "  help\t顯示本說明")
	_ = w.Flush()
	fmt.Println()
	fmt.Println("範例：")
	fmt.Println("  # 清除所有事件記錄")
	fmt.Println("  xwatch db clear")
	fmt.Println()
	fmt.Println("注意事項：")
	fmt.Println("  - db clear 執行前會先停止 Windows 服務，完成後服務不會自動重啟")
	fmt.Println("  - 清除操作不可復原，請確認後再執行")
	fmt.Println("  - 需要系統管理員權限")
}

// printExportHelp 顯示 export 指令的詳細說明。
func printExportHelp() {
	fmt.Println()
	fmt.Println("export — 匯出 XWatch 監控事件記錄")
	fmt.Println()
	fmt.Println("用法：")
	fmt.Println("  export [--since TIME] [--until TIME] [--limit N] [--format TYPE] [--all] [--bom] [--out PATH]")
	fmt.Println()
	fmt.Println("參數說明：")
	w := tabwriter.NewWriter(os.Stdout, 2, 0, 2, ' ', 0)
	fmt.Fprintln(w, "  --since RFC3339\t篩選起始時間，採 RFC3339 格式（如 2026-03-01T00:00:00+08:00）。")
	fmt.Fprintln(w, "  \t省略時不限制起始時間。")
	fmt.Fprintln(w, "  --until RFC3339\t篩選截止時間，採 RFC3339 格式。省略時不限制截止時間。")
	fmt.Fprintln(w, "  --limit N\t最大匯出筆數（預設：1000）。指定 --all 時此參數無效。")
	fmt.Fprintln(w, "  --all\t匯出所有事件，忽略 --since / --until / --limit 限制。")
	fmt.Fprintln(w, "  --format TYPE\t匯出格式（預設：json）：")
	fmt.Fprintln(w, "  \t  json   完整 JSON 陣列")
	fmt.Fprintln(w, "  \t  jsonl  每行一筆 JSON（JSON Lines）")
	fmt.Fprintln(w, "  \t  text   人類可讀的文字格式")
	fmt.Fprintln(w, "  --bom\t在輸出開頭加入 UTF-8 BOM，供 Windows 記事本正確顯示中文。")
	fmt.Fprintln(w, "  --out PATH\t輸出檔案路徑。使用 '-' 輸出至 stdout。")
	fmt.Fprintln(w, "  \t省略時自動命名並存入 %ProgramData%\\go-xwatch\\xwatch-export-files\\。")
	_ = w.Flush()
	fmt.Println()
	fmt.Println("範例：")
	fmt.Println("  # 匯出最近 1000 筆事件為 JSON（預設模式）")
	fmt.Println("  xwatch export")
	fmt.Println()
	fmt.Println("  # 匯出所有事件輸出至 stdout")
	fmt.Println("  xwatch export --all --out -")
	fmt.Println()
	fmt.Println("  # 篩選特定日期範圍，以 text 格式輸出並加 BOM（供記事本閱讀）")
	fmt.Println("  xwatch export --since 2026-03-01T00:00:00+08:00 --until 2026-03-02T00:00:00+08:00 --format text --bom")
	fmt.Println()
	fmt.Println("  # 匯出最新 50 筆，存入指定檔案")
	fmt.Println("  xwatch export --limit 50 --out D:\\logs\\events.json")
	fmt.Println()
	fmt.Println("  # 匯出全部事件為 JSON Lines 格式")
	fmt.Println("  xwatch export --all --format jsonl --out D:\\logs\\events.jsonl")
}
